### ISSUE TITLE
NPE due to missing units in legacy Reports

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-modules-public#43]
We removed the units from the serialization of the text renderer in Mango 3.6.0.  This means that the legacy report lost the units and fails on execution.

The solution is to upgrade the reports table and add units to it and ensure they are set on the renderer.

```
ERROR 2019-04-24T10:34:52,021 (com.serotonin.m2m2.rt.maint.BackgroundProcessingImpl$WorkItemRunnable.run:679) - Error in work item 
java.lang.NullPointerException: null
	at com.serotonin.m2m2.view.text.AnalogRenderer.getText(AnalogRenderer.java:106) ~[mango-3.6.0-beta.3.jar:?]
	at com.serotonin.m2m2.view.text.AnalogRenderer.getTextImpl(AnalogRenderer.java:100) ~[mango-3.6.0-beta.3.jar:?]
	at com.serotonin.m2m2.view.text.BaseTextRenderer.getText(BaseTextRenderer.java:81) ~[mango-3.6.0-beta.3.jar:?]
	at com.serotonin.m2m2.view.text.TextRenderer.getText(TextRenderer.java:58) ~[mango-3.6.0-beta.3.jar:?]
	at com.serotonin.m2m2.reports.web.ReportChartCreator$StreamHandler.startPoint(ReportChartCreator.java:619) ~[?:?]
	at com.serotonin.m2m2.reports.ReportDao.reportInstanceDataNoSQL(ReportDao.java:710) ~[?:?]
	at com.serotonin.m2m2.reports.web.ReportChartCreator.createContent(ReportChartCreator.java:138) ~[?:?]
	at com.serotonin.m2m2.reports.web.ReportWorkItem.execute(ReportWorkItem.java:182) ~[?:?]
	at com.serotonin.m2m2.rt.maint.BackgroundProcessingImpl$WorkItemRunnable.run(BackgroundProcessingImpl.java:676) ~[mango-3.6.0-beta.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by terrypacker** [comment]
Fixed by https://github.com/infiniteautomation/ma-modules-public/commit/247dfbce9268512de411259510b98c1c1ff33e49
