### ISSUE TITLE
Mango API - POST VO with ID fails with NPE

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-modules-public#46]
This was found on `POST v2/data-sources` but would apply to all create vo endpoints.  If the user supplies an `id` in the JSON then the DAO layer will think it is updating a vo and try to extract it from the database and fail with a NPE at:

```
java.lang.NullPointerException: null
	at com.serotonin.m2m2.db.dao.AbstractDao.update(AbstractDao.java:263) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.AbstractDao.update(AbstractDao.java:1) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.AbstractBasicDao.update(AbstractBasicDao.java:628) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.AbstractBasicDao.save(AbstractBasicDao.java:538) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.AbstractBasicDao.save(AbstractBasicDao.java:526) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.DataSourceDao.updateDataSource(DataSourceDao.java:187) ~[classes/:?]
	at com.serotonin.m2m2.db.dao.DataSourceDao.saveDataSource(DataSourceDao.java:166) ~[classes/:?]
	at com.serotonin.m2m2.rt.RuntimeManagerImpl.saveDataSource(RuntimeManagerImpl.java:323) ~[classes/:?]
	at com.infiniteautomation.mango.spring.service.DataSourceService.insert(DataSourceService.java:61) ~[classes/:?]
	at com.infiniteautomation.mango.spring.service.DataSourceService.insert(DataSourceService.java:1) ~[classes/:?]
	at com.infiniteautomation.mango.spring.service.AbstractVOService.insertFull(AbstractVOService.java:195) ~[classes/:?]
	at com.infiniteautomation.mango.rest.v2.DataSourcesRestController.save(DataSourcesRestController.java:123) ~[?:?]
```

**Comment by terrypacker** [comment]
Correct solution is to add a check in the DataSourceService.insert method to ensure that an ID is not set.
